services:
    #
    # commands services
    #
    sfynx.core.command.database.drop:
        class: 'Sfynx\CoreBundle\Layers\Application\Cmd\dropDatabaseCommand'
        tags:
            - { name: console.command }