default:
    mapping:
        x-providers: [orm, couchdb]
        x-entities:
          Group:
            x-fields:
              id:
                name: entityId
                type: valueObject
                voName: IdVO
                primaryKey: true
#                mapping:
#                  targetEntity: Sfynx\AuthBundle\Domain\Entity\Group
#                  formData:
#                      manager: 'Sfynx\AuthBundle\Domain\Service\Group\Manager\EntityManager as GroupManager'
              group:
                type: valueObject
                voName: GroupVO
        x-valueObjects:
          IdVO:
            type: Sfynx\CoreBundle\Layers\Domain\ValueObject\IdVO
            x-fields:
              id:
                type: id
          GroupVO:
            type: Domain\ValueObject\GroupVO
            x-fields:
              name:
                type: string
                required: true
              enabled:
                type: boolean
                defaultValue: true
#                required: false
              roles:
                type: array
                form:
                  type: array
                  serviceType: sfynx_security_roles
                required: true
                multiple: true
                expanded: false
              permissions:
                type: array
                form:
                  type: array
                  serviceType: sfynx_security_permissions
                required: true
                multiple: true
                expanded: false