default:
    widgets:
        application:
            widget_cqrs_command:
                - MovieFormCommand:
                    create: true
                    class: MovieFormCommand
                    options:
                        models:
                          0:
                            class: 'Sfynx\CoreBundle\Generator\Domain\Component\File\HandlerModel\Observer\CommandQueryObject'
                            parameters:
                              performMethods:
                                - 'Sfynx\CoreBundle\Generator\Domain\Component\File\MethodModel\Construct'
                                - 'Sfynx\CoreBundle\Generator\Domain\Component\File\MethodModel\CreateFromNative'
                              createFromNativeType: false
            widget_cqrs_command_validator_specification:
                class: Validation\SpecHandler\MovieFormCommandSpecHandler
                arguments:
                - '$commandHandlerResult'
            widget_cqrs_command_validator_validation:
                class: Validation\ValidationHandler\MovieFormCommandValidationHandler
                arguments:
                - '$commandHandlerResult'
                - 'new SymfonyValidatorStrategy'
                - 'false'
            widget_service_app_class:
            - SymfonyValidatorStrategy:
                  create: false
                  class: 'Sfynx\CoreBundle\Layers\Application\Validation\Validator\SymfonyValidatorStrategy'
                  arguments: ['Symfony\Component\Validator\Validator\ValidatorInterface']
            widget_validation_type:
                class: MovieType
                arguments: ~
