default:
    widgets:
        presentation:
            widget_coordination:
                class: FormCoordination
                arguments:
                - '$workflowHandler'
                extends: ~
                options:
                    implements: ~
                    uses:
                      - 'Symfony\Component\HttpFoundation\Response'
                      - 'Exception'
                      - 'Sfynx\CoreBundle\Layers\Infrastructure\Exception\Entity\ViolationEntityException'
                      - 'Sfynx\CoreBundle\Layers\Infrastructure\Exception\Entity\NotFoundEntityException'
                    traits: ['Sfynx\CoreBundle\Layers\Presentation\Coordination\Generalisation\Traits\TraitParam']
                body:
                - codeComment1:
                      design: 'code'
                      content:
                      - 'try {'
                      - "   // 1. Transform options to Command."
                - updateCommand:
                      design: 'adapter'
                      class: Sfynx\CoreBundle\Layers\Presentation\Adapter\Command\CommandAdapter
                      arguments:
                      - 'new MovieFormCommand'
                      calls:
                      - [ createCommandFromRequest, [ 'new MovieFormRequest', 'false' ] ]
                - codeComment2:
                      design: 'code'
                      content: "// 2. Implement the command workflow"
                - commandWorkflow:
                      design: 'observer'
                      class: Sfynx\CoreBundle\Layers\Application\Command\Workflow\CommandWorkflow
                      calls:
                      - [ attach, [ 'new OBMovieEntityEdit' ] ]
                      - [ attach, [ 'new OBMovieEntityCreate' ] ]
                - codeComment3:
                      design: 'code'
                      content: "// 3. Implement decorator to apply the command workflow from the command"
                - commandHandlerResult:
                      design: 'decorator'
                      class: Sfynx\CoreBundle\Layers\Application\Command\Handler\CommandHandler
                      arguments:
                      - '$commandWorkflow'
#                            - '[$this->movieManager, $this->genreManager, $this->priceManager]'
                      - '[MyContext\Domain\Service\Entity\Movie\Manager\MovieManager, MyContext\Domain\Service\Entity\Genre\Manager\GenreManager, MyContext\Domain\Service\Entity\Price\Manager\PriceManager]'
                      handlers: [ 'MovieFormCommandValidationHandler', 'MovieFormCommandSpecHandler']
                      calls:
                      - [ process, [ '$updateCommand' ] ]
                - codeln1:
                      design: 'code'
                      content:
                      - "// 4. Implement the Response workflow"
                      - "$this->setParam('templating', '@Business/Movie/edit.html.twig');"
                - workflowHandler:
                      design: 'observer'
                      class: Sfynx\CoreBundle\Layers\Application\Common\Handler\WorkflowHandler
                      calls:
                      - [ attach, [ 'new OBMovieCreateFormData' ] ]
                      - [ attach, [ 'new OBCreateCommandFormView' ] ]
                      - [ attach, [ 'new OBInjectFormErrors' ] ]
                      - [ attach, [ 'new OBMovieCreateFormBody' ] ]
                      - [ attach, [ 'new OBCreateResponseHtml' ] ]
                - responseHandlerResult:
                      design: 'handler'
                      class: Sfynx\CoreBundle\Layers\Application\Response\Handler\ResponseHandler
                      arguments:
                      - '$workflowHandler'
                      calls:
                      - [ process, [ '$commandHandlerResult' ] ]
                - codeln2:
                      design: 'code'
                      content:
                      - "    $response = $responseHandlerResult->getResponse();"
                      - ""
                      - "    $this->logger->info('Request has been sent from this Command', ['command' => $updateCommand]);"
                      - '}  catch (NotFoundEntityException $e) {'
                      - "    $this->logger->error('Request has failed with NotFoundEntityException exception', ['command' => $updateCommand]);"
                      - '    $response = new Response();'
                      - '    $response->setStatusCode(Response::HTTP_NOT_FOUND);'
                      - '    $response->setContent($e->getMessage());'
                      - '}  catch (ViolationEntityException $e) {'
                      - "    $this->logger->error('Request has failed with ViolationEntityException exception', ['command' => $updateCommand]);"
                      - '    $response = new Response();'
                      - '    $response->setStatusCode(Response::HTTP_CONFLICT);'
                      - '    $response->setContent($e->getMessage());'
                      - '}  catch (Exception $e) {'
                      - "    $this->logger->error('Request has failed with HTTP_SERVICE_UNAVAILABLE exception', ['command' => $updateCommand]);"
                      - '    $response = new Response();'
                      - '    $response->setStatusCode(Response::HTTP_SERVICE_UNAVAILABLE);'
                      - '    $response->setContent($e->getMessage());'
                      - '}'
                      - ''
                      - 'return $response;'
            widget_request:
                class: MovieFormRequest
                arguments:
                - 'Sfynx\CoreBundle\Layers\Domain\Service\Request\Generalisation\RequestInterface'
